# Generated by Django 2.2.6 on 2021-03-07 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20201021_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='access_tkn',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='item_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='webhook',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('official_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('account_id', models.TextField()),
                ('balance_available', models.IntegerField()),
                ('balance_current', models.IntegerField()),
                ('iso_currency_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('limit', models.IntegerField(blank=True, default=None, null=True)),
                ('sub_type', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('acc_type', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('mask', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
