# Generated by Django 2.2.6 on 2021-03-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210307_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance_available',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_current',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
